model: gemini-2.5-flash
url: https://generativelanguage.googleapis.com/v1beta/openai/
api_key: Your API Key Here
inference_parameters:
  extra_body:
    google:
      thinking_config:
        thinking_budget: 0
        include_thoughts: true

# extra_body={
#     'extra_body': {
#       "google": {
#         "thinking_config": {
#           "thinking_budget": 800,
#           "include_thoughts": True
#         }
#       }
#     }
#   }
