model: gemini-2.5-flash # or gemini-1.5-flash, gemini-1.5-pro
url: https://generativelanguage.googleapis.com/v1beta/openai/
api_key: ${GEMINI_API_KEY} # Get your API key from https://aistudio.google.com/apikey
inference_parameters:
  max_tokens: 65536
  temperature: 0.7
  extra_body:
    extra_body:
      google:
        thinking_config:
          thinking_budget: -1
          include_thoughts: true
