model: deepseek-reasoner
url: https://api.deepseek.com
api_key: ${DEEPSEEK_API_KEY} # Set this in .env file or environment
inference_parameters:
  temperature: 0.6
  top_p: 0.95
  max_tokens: 65536
tokenizer: deepseek-ai/DeepSeek-R1
