name: PR Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-and-typecheck:
    name: Lint and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Run ruff check
        run: |
          uv run ruff check

      - name: Run ruff format check
        run: |
          uv run ruff format --check

      - name: Run ty type check
        run: |
          uv run ty check

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Run tests (if available)
        run: |
          # Add your test command here when you have tests
          # uv run pytest
          echo "No tests configured yet"
        continue-on-error: true
